# REST API 실습

22th DE 김원

## Python에서

In [1]:
import requests
# GET 요청 보내기
response = requests.get('https://reqres.in/api/users?page=2')

# 응답 확인
if response.status_code == 200:
    res = response.json()
    print(res)
else:
    print('요청에 실패했습니다. 상태 코드:', res.status_code)

{'page': 2, 'per_page': 6, 'total': 12, 'total_pages': 2, 'data': [{'id': 7, 'email': 'michael.lawson@reqres.in', 'first_name': 'Michael', 'last_name': 'Lawson', 'avatar': 'https://reqres.in/img/faces/7-image.jpg'}, {'id': 8, 'email': 'lindsay.ferguson@reqres.in', 'first_name': 'Lindsay', 'last_name': 'Ferguson', 'avatar': 'https://reqres.in/img/faces/8-image.jpg'}, {'id': 9, 'email': 'tobias.funke@reqres.in', 'first_name': 'Tobias', 'last_name': 'Funke', 'avatar': 'https://reqres.in/img/faces/9-image.jpg'}, {'id': 10, 'email': 'byron.fields@reqres.in', 'first_name': 'Byron', 'last_name': 'Fields', 'avatar': 'https://reqres.in/img/faces/10-image.jpg'}, {'id': 11, 'email': 'george.edwards@reqres.in', 'first_name': 'George', 'last_name': 'Edwards', 'avatar': 'https://reqres.in/img/faces/11-image.jpg'}, {'id': 12, 'email': 'rachel.howell@reqres.in', 'first_name': 'Rachel', 'last_name': 'Howell', 'avatar': 'https://reqres.in/img/faces/12-image.jpg'}], 'support': {'url': 'https://reqres.in/#support-heading', 'text': 'To keep ReqRes free, contributions towards server costs are appreciated!'}}

In [2]:
res

{'page': 2,
 'per_page': 6,
 'total': 12,
 'total_pages': 2,
 'data': [{'id': 7,
   'email': 'michael.lawson@reqres.in',
   'first_name': 'Michael',
   'last_name': 'Lawson',
   'avatar': 'https://reqres.in/img/faces/7-image.jpg'},
  {'id': 8,
   'email': 'lindsay.ferguson@reqres.in',
   'first_name': 'Lindsay',
   'last_name': 'Ferguson',
   'avatar': 'https://reqres.in/img/faces/8-image.jpg'},
  {'id': 9,
   'email': 'tobias.funke@reqres.in',
   'first_name': 'Tobias',
   'last_name': 'Funke',
   'avatar': 'https://reqres.in/img/faces/9-image.jpg'},
  {'id': 10,
   'email': 'byron.fields@reqres.in',
   'first_name': 'Byron',
   'last_name': 'Fields',
   'avatar': 'https://reqres.in/img/faces/10-image.jpg'},
  {'id': 11,
   'email': 'george.edwards@reqres.in',
   'first_name': 'George',
   'last_name': 'Edwards',
   'avatar': 'https://reqres.in/img/faces/11-image.jpg'},
  {'id': 12,
   'email': 'rachel.howell@reqres.in',
   'first_name': 'Rachel',
   'last_name': 'Howell',
   'avatar': 'https://reqres.in/img/faces/12-image.jpg'}],
 'support': {'url': 'https://reqres.in/#support-heading',
  'text': 'To keep ReqRes free, contributions towards server costs are appreciated!'}}

In [3]:
res['data'][0]

{'id': 7,
 'email': 'michael.lawson@reqres.in',
 'first_name': 'Michael',
 'last_name': 'Lawson',
 'avatar': 'https://reqres.in/img/faces/7-image.jpg'}

In [4]:
import pandas as pd
df = pd.DataFrame(res['data'])
df

,id,email,first_name,last_name,avatar
0,7,michael.lawson@reqres.in,Michael,Lawson,https://reqres.in/img/faces/7-image.jpg
1,8,lindsay.ferguson@reqres.in,Lindsay,Ferguson,https://reqres.in/img/faces/8-image.jpg
2,9,tobias.funke@reqres.in,Tobias,Funke,https://reqres.in/img/faces/9-image.jpg
3,10,byron.fields@reqres.in,Byron,Fields,https://reqres.in/img/faces/10-image.jpg
4,11,george.edwards@reqres.in,George,Edwards,https://reqres.in/img/faces/11-image.jpg
5,12,rachel.howell@reqres.in,Rachel,Howell,https://reqres.in/img/faces/12-image.jpg

## terminal에서

가장 간단한 요청입니다 curl + 요청을 보낼 주소 위는 코랩이기 때문에 터미널명령어를 !앞에 붙여 실행합니다 터미널에서는 !안붙여도 괜찮아요!!

In [5]:
!curl https://reqres.in/api/users?page=2

Curl에 여러가지 옵션을 추가할 수 있습니다

-X : HTTP 메서드 지정
<br>

GET: 리소스를 가져오기 위한 요청입니다. 기본적으로 curl이 사용하는 메서드입니다.<br>
POST: 리소스를 생성하기 위한 요청입니다. 데이터를 서버로 전송할 때 사용됩니다.<br>
PUT: 리소스를 수정하기 위한 요청입니다. 전체 리소스를 업데이트합니다.<br>
PATCH: 리소스를 일부 수정하기 위한 요청입니다. 부분적인 업데이트를 수행할 때 사용됩니다.<br>
DELETE: 리소스를 삭제하기 위한 요청입니다.

<br>

-H : header 설정 header란 무엇일까? - 범위를 벗어나므로 신원을 확인하거나, 추가적인 정보가 담겨있는 부분: <br> => 메타데이터가 담겨있는 부분입니다!  <br>

-d : data의 약자로 데이터를 넘겨줍니다


<br>

아래의 예시의 경우, 게시판 홈페이지에 사람을 추가하는 예시! <br>

리소스를 생성하기 때문에 POST method로, 추가해야할 데이터를 -d 인자로 넘겨줍니다

In [6]:
!curl -X POST -H "Content-Type: application/json" -d '{"name": "John", "age":30}' https://reqres.in/api/users

위 코드를 실행하면, 정상응답이 나오는 경우 reqres.in 페이지에 /api/users에 새로운 유저를 등록 요청하는 request입니다!

### 위를 파이썬 버전으로

In [7]:
import requests
import json

url = 'https://reqres.in/api/users'
headers = {'Content-Type': 'application/json'}
data = {'name': 'John', 'age': 30}


# post method로 요청

response = requests.post(url, headers=headers, data=json.dumps(data))

if response.status_code == 201: # 상태코드가 201이라면(201 : 요청 정상처리 상태코드 )
    result = response.json()
    print('사용자 생성 완료:', result)
else:
    print('요청에 실패했습니다. 상태 코드:', response.status_code)

사용자 생성 완료: {'name': 'John', 'age': 30, 'id': '674', 'createdAt': '2023-07-17T14:40:13.361Z'}

In [8]:
res['data'][0]

{'id': 7,
 'email': 'michael.lawson@reqres.in',
 'first_name': 'Michael',
 'last_name': 'Lawson',
 'avatar': 'https://reqres.in/img/faces/7-image.jpg'}

# 페이지를 순회하며 데이터 프레임 만들기! + 약간의 전처리

In [9]:
import requests
# GET 요청 보내기
response = requests.get('https://reqres.in/api/users?page=2')

# 응답 확인
if response.status_code == 200:
    res = response.json()
    print(res)
else:
    print('요청에 실패했습니다. 상태 코드:', res.status_code)

{'page': 2, 'per_page': 6, 'total': 12, 'total_pages': 2, 'data': [{'id': 7, 'email': 'michael.lawson@reqres.in', 'first_name': 'Michael', 'last_name': 'Lawson', 'avatar': 'https://reqres.in/img/faces/7-image.jpg'}, {'id': 8, 'email': 'lindsay.ferguson@reqres.in', 'first_name': 'Lindsay', 'last_name': 'Ferguson', 'avatar': 'https://reqres.in/img/faces/8-image.jpg'}, {'id': 9, 'email': 'tobias.funke@reqres.in', 'first_name': 'Tobias', 'last_name': 'Funke', 'avatar': 'https://reqres.in/img/faces/9-image.jpg'}, {'id': 10, 'email': 'byron.fields@reqres.in', 'first_name': 'Byron', 'last_name': 'Fields', 'avatar': 'https://reqres.in/img/faces/10-image.jpg'}, {'id': 11, 'email': 'george.edwards@reqres.in', 'first_name': 'George', 'last_name': 'Edwards', 'avatar': 'https://reqres.in/img/faces/11-image.jpg'}, {'id': 12, 'email': 'rachel.howell@reqres.in', 'first_name': 'Rachel', 'last_name': 'Howell', 'avatar': 'https://reqres.in/img/faces/12-image.jpg'}], 'support': {'url': 'https://reqres.in/#support-heading', 'text': 'To keep ReqRes free, contributions towards server costs are appreciated!'}}

# 원래 여러분들이 사용하실 때는...

보통 API의 호출양이 지정되어 있어서, API 세션 아이디, 키가 보통 필요해요!

</br>

밑에 하고자 했던 코드는 여러페이지에 걸쳐 순회해서 데이터프레임으로 만드는 과정을 보여드리려고했는데,
저게 api가 연습용 서버여서 조금 호출 횟수에 제한된 것 같네요!! 원래 1페이지 부터 11페이지까지 6 x 11 행이 나와야하는데, 무료이다보니 서버에 부담이 되어 time.sleep(5)로 해봤는데도 안되네요! 하여튼 예시로 참고하면 좋을 것 같습니다!

In [10]:
import requests
import pandas as pd
import time

# 빈 데이터프레임 생성
df_combined = pd.DataFrame()

# 페이지 순회
for page in range(1, 11):
    # GET 요청 보내기
    url = f'https://reqres.in/api/users?page={page}'
    response = requests.get(url)

    # 응답 확인
    if response.status_code == 200:
        data = response.json()
        users = data['data']

        # 데이터프레임으로 변환
        df = pd.DataFrame(users)

        # 데이터프레임 결합
        df_combined = pd.concat([df_combined, df], ignore_index=True)
    else:
        print(f'페이지 {page} 요청에 실패했습니다. 상태 코드:', response.status_code)

# 합쳐진 데이터프레임 출력 (아쉽게도 안됨)
df_combined

,id,email,first_name,last_name,avatar
0,1,george.bluth@reqres.in,George,Bluth,https://reqres.in/img/faces/1-image.jpg
1,2,janet.weaver@reqres.in,Janet,Weaver,https://reqres.in/img/faces/2-image.jpg
2,3,emma.wong@reqres.in,Emma,Wong,https://reqres.in/img/faces/3-image.jpg
3,4,eve.holt@reqres.in,Eve,Holt,https://reqres.in/img/faces/4-image.jpg
4,5,charles.morris@reqres.in,Charles,Morris,https://reqres.in/img/faces/5-image.jpg
5,6,tracey.ramos@reqres.in,Tracey,Ramos,https://reqres.in/img/faces/6-image.jpg
6,7,michael.lawson@reqres.in,Michael,Lawson,https://reqres.in/img/faces/7-image.jpg
7,8,lindsay.ferguson@reqres.in,Lindsay,Ferguson,https://reqres.in/img/faces/8-image.jpg
8,9,tobias.funke@reqres.in,Tobias,Funke,https://reqres.in/img/faces/9-image.jpg
9,10,byron.fields@reqres.in,Byron,Fields,https://reqres.in/img/faces/10-image.jpg
10,11,george.edwards@reqres.in,George,Edwards,https://reqres.in/img/faces/11-image.jpg
11,12,rachel.howell@reqres.in,Rachel,Howell,https://reqres.in/img/faces/12-image.jpg

# 과제 !! 나쁜 사람 아닙니다


**개념 요약!! 아래 마크다운을 채워주세요 !! **

챗지피티 사용금지


## API란 -> Application Programming Interface의 줄임말로, 애플리케이션 간의 정보를 교환할 때 일정한 규칙에 따라 정보를 교환할 수 있도록 하는 방식.

## REST API란 -> REpresentational State Transfer Application Programming Interface의 줄임말로, 서버의 어떤 정보의 연산을 수행하기 위해 정해진 의사소통 규칙인 API를 따라 서버에 요청하는 것.

## 각각에 대응하는 HTTP의 메서드를 적어주세요

### Create -> 리소스 조회(GET)
### Read -> 리소스 등록(POST)
### Update -> 리소스 대체 없으면 생성(PUT) / 리소스 부분 변경(PATCH)
### Delete -> 리소스 삭제(DELETE)

## 실습 과제 1 공식문서를 읽고 아래의 예시코드에 파라미터를 바꿔서 보낸 결과 확인하기!!

공식문서에 파라미터들을 직접 넘겨줘서 요청을 보내면 됩니다!

<https://punkapi.com/documentation/v2>

In [11]:
!curl https://api.punkapi.com/v2/beers



```
response = requests.get('https://reqres.in/api/users?page=2&per_page=10')
response.get(url,params= {'page': 2, 'per_page':10 })
```



위에 두개는 같은 요청입니다! 뒤에 파라미터들이 ?으로 , 파라미터가 여러개일 경우 &으로 연결됩니다!

In [12]:
import requests
import json
import time

url = 'https://api.punkapi.com/v2/beers'
headers = {'Content-Type': 'application/json'}
# 파라미터로 인자 넘겨줄 수 있음!!
# 아래 params 코드에 인자들을 공식문서를 확인하여 추가하시거나 바꿔주세요!!
params= {'page': 3, 'abv':20 }

response = requests.get(url, headers=headers,params=params)

if reponse.status_code == 200:
    result = response.json()
    print('받아온 데이터:', result)
else:
    print('요청에 실패했습니다. 상태 코드:', response.status_code)

NameError: name 'reponse' is not defined

In [17]:
import pandas as pd

df = pd.DataFrame(result)
df

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,...,srm,ph,attenuation_level,volume,boil_volume,method,ingredients,food_pairing,brewers_tips,contributed_by
0,51,TM10,Liquid Art.,04/2010,Brewed for the Tate Modern’s 10th Anniversary....,https://images.punkapi.com/v2/51.png,5.50,20,1005,1048.0,...,7.00,4.2,89.60,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 63, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...","[Tom yum soup, Andhra chicken pickle curry, Bu...","For a fresh and fiery hit, put some ginger int...",Sam Mason <samjbmason>
1,52,Paradox Islay,Ubiquitous Imperial Stout.,04/2007,In 2006 James and Martin hijacked a beer dinne...,https://images.punkapi.com/v2/52.png,10.00,55,1014,1090.0,...,152.00,4.4,84.40,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Ancho chilli beef taco, Chocolate gateaux, Ru...",The beauty of this beer is in how brilliantly ...,Sam Mason <samjbmason>
2,53,Baby Dogma,Session Scotch Ale.,09/2013,A baby Scotch ale with dry and toasty malt fla...,https://images.punkapi.com/v2/keg.png,4.50,35,1013,1048.0,...,20.00,4.4,72.90,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 66, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[French onion soup, Braised pheasant, Caramel ...",The addition of Weyermann Beech Smoked malt cr...,Ali Skinner <AliSkinner>
3,54,Albino Squid Assasin,Red Rye IPA,11/2015,This tentacled terminator packs a punch - ten ...,https://images.punkapi.com/v2/54.png,7.40,65,1012,1069.0,...,30.00,4.2,82.60,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...",[Rocket and mozzarella salad with a cracked pe...,20% specialty malts in this grist can create p...,Matt Ball <GeordieMatt>
4,55,Amarillo - IPA Is Dead,Single Hop India Pale Ale.,01/2013,Citrus fruit. Lots of citrus fruit. Think bloo...,https://images.punkapi.com/v2/55.png,7.20,70,1012,1067.0,...,15.00,4.4,82.10,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Bratwurst sausage with spicy mustard, Fried A...",Use the freshest hops for the most impact. It ...,Sam Mason <samjbmason>
5,56,Black Eyed King Imp,Barrel-Aged Prototype Cocoa Psycho.,11/2012,"An early Cocoa Psycho recipe that we loved, bu...",https://images.punkapi.com/v2/56.png,9.50,85,1022,1095.0,...,125.00,4.4,76.80,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...",{'malt': [{'name': 'Extra Pale - Spring Blend'...,"[Beef chilli made with cocoa powder, Dark choc...",There is a huge amount of roasted malts in thi...,Sam Mason <samjbmason>
6,57,Prototype 27,Vibrant Smoky Pink IPA.,04/2010,Hardcore IPA with raspberries aged in Caol Ila...,https://images.punkapi.com/v2/57.png,9.20,149,1014,1083.0,...,9.80,4.4,83.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...","[Strong blue cheese, Cranachan, Chicago style ...",Soak some oak chips in Caol Ila whisky to get ...,Sam Mason <samjbmason>
7,58,Coffee Imperial Stout,Beats a Cup of Joe.,11/2008,"This beer was released as both as ""Danish Beer...",https://images.punkapi.com/v2/58.png,9.00,65,1019,1080.0,...,49.00,4.4,76.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 64, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Gooey chocolate brownies, Chicken fried steak...",Grind the coffee as if making an espresso to r...,Sam Mason <samjbmason>
8,59,Mandarina Bavaria - IPA Is Dead,Single Hop India Pale Ale.,03/2015,"From the central European plains of Germany, c...",https://images.punkapi.com/v2/59.png,7.20,100,1010,1064.0,...,6.00,4.4,84.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Lavender and thyme roast beef, Spicy kung po ...",We've mentioned the importance of fresh hops p...,Sam Mason <samjbmason>
9,60,Dogma,Revamped Wee Heavy. Luscious. Malty. Fruity.,07/2013,"Brewed with over ten different types of malt, ...",https://images.punkapi.com/v2/60.png,7.50,30,1023,1080.0,...,23.00,4.5,70.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale', 'amount': {'val...","[Mature cheddar with red onion chutney, Honey ...",There's a lot of specialty malt in the mash. M...,Ali Skinner <AliSkinner>
10,61,Magic Stone Dog (w/Magic Rock & Stone Brewing ...,Session Farmhouse IPA - Stone / Magic Rock Col...,06/2014,A session IPA brewed with a diverse grain bill...,https://images.punkapi.com/v2/61.png,4.60,30,1008,1043.0,...,7.50,4.4,81.40,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Halibut with caper brown butter, Creamy gorgo...",Start the fermentation off at 20 ̊C and allow ...,Sam Mason <samjbmason>
11,62,AB:08,Deconstructed Blonde Imperial Stout.,11/2011,"Flavours and aromas you'd expect from a Stout,...",https://images.punkapi.com/v2/62.png,10.43,65,1016,1095.0,...,11.50,4.4,83.20,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Caramelised scallops with burnt apple puree, ...",Add all twist ingredients to Fermentation Vess...,Sam Mason <samjbmason>
12,63,Sunk Punk,Ocean Fermented Lager.,09/2011,It's rumoured just a drop can calm the fierces...,https://images.punkapi.com/v2/63.png,7.10,68,1010,1056.0,...,7.00,4.4,82.10,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Salt baked cod with lemon and dill butter, Be...",Keep the fermentation temperature as steady as...,Sam Mason <samjbmason>
13,64,Sub Hop,Hopped-Up Imperial Pilsner.,06/2014,Brewed for the opening of our first bar in Ita...,https://images.punkapi.com/v2/64.png,8.00,35,1016,1077.0,...,7.50,4.4,79.20,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Seared lemon and herb salmon, Crab linguine, ...",Sit this beer aside for a month to allow it to...,Sam Mason <samjbmason>
14,65,Bracken's Porter,A Tribute To Our Favourite 4 Pawed Friend.,03/2013,The beer was named Bracken’s Porter as a tribu...,https://images.punkapi.com/v2/keg.png,5.00,50,1010,1049.0,...,55.00,4.4,79.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...",[Grilled vegetable and chicken teriyaki skewer...,Try to replicate London’s highly carbonated wa...,Sam Mason <samjbmason>
15,66,Tokyo Rising Sun - Lowland,A Beautiful Accident.,06/2009,"A forgotten gem in the deepest, darkest corner...",https://images.punkapi.com/v2/66.png,13.20,85,1023,1125.0,...,71.00,4.4,82.17,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Duck liver paté, Mutton stew, Kirsch chocola...",Leave on wood for as long as you dare. If poss...,Sam Mason <samjbmason>
16,67,Hunter Foundation Pale Ale,American Pale Ale.,05/2012,This straight-up US style pale ale uses some o...,https://images.punkapi.com/v2/67.png,5.40,35,1008,1050.0,...,5.75,4.4,84.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 63, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Monterey Jack stuffed grilled jalepenos, Barb...","To dry the beer out, mash at a slightly lower ...",Sam Mason <samjbmason>
17,68,Hype,New Zealand Pale Ale.,08/2007,A perfect pale ale showcase for the tropical p...,https://images.punkapi.com/v2/keg.png,4.10,65,1010,1042.0,...,8.50,4.4,76.20,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Quince cheese, Shredded chicken and mango sal...","After the beer has fermented, leave it to rest...",Sam Mason <samjbmason>
18,69,AB:16,Coffee-Infused Belgian Quad.,02/2014,"On the nose, clove and nutmeg, cafe au lait, s...",https://images.punkapi.com/v2/69.png,10.60,55,1012,1090.0,...,15.00,4.4,86.70,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Roasted duck, Gorgonzola and rye nut bread wi...","For the traditional cellering, age this beer i...",Ali Skinner <AliSkinner>
19,70,Sunmaid Stout,Rum & Raisin Imperial Stout.,12/2011,Brewed by Chris Sartori from Stone Brewing Com...,https://images.punkapi.com/v2/keg.png,10.20,50,1102,1026.0,...,100.00,4.4,74.50,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Pale Ale - Tipple', 'amoun...",[Lapin aux pruneaux (braised rabbit with prune...,Take small volume of wort out of the run off a...,Sam Mason <samjbmason>
20,71,Pale - Russian Doll,Nesting Hop Bomb.,08/2014,The levels of hops vary throughout the range. ...,https://images.punkapi.com/v2/71.png,4.00,35,1010,1041.0,...,22.50,5.2,75.60,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Roast chicken with vegetables and wild rice, ...",Create balance through experimentation with th...,Sam Mason <samjbmason>
21,72,Whisky Sour - B-Sides,Pilot Brew - Deconstructed Whisky Sour.,03/2015,"Deconstructed whisky sour, reconstructed as a ...",https://images.punkapi.com/v2/keg.png,7.00,20,1021,1081.0,...,6.00,3.2,74.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 60, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Potted fresh & smoked salmon, Spiced nut loaf...",Lemon poppyseed donuts.,Sam Mason <samjbmason>
22,73,Black Eyed King Imp - Vietnamese Coffee Edition,Vietnamese Coffee Edition.,12/2014,This is the Vietnamese Coffee Edition. At 12.7...,https://images.punkapi.com/v2/73.png,12.70,85,1038,1113.5,...,125.00,5.2,76.80,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Bacon sandwich with brown sauce, 20hr smoked ...",Buying top notch coffee beans make a huge diff...,Sam Mason <samjbmason>
23,74,Eurotrash,Belgian Blonde.,10/2009,"Trashy Blonde with a Belgian Twist. Clove oil,...",https://images.punkapi.com/v2/keg.png,4.10,52,1010,1041.0,...,8.50,5.2,76.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 66, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Grilled fish salad, Angelfood cake, Pad Thai]",Don't be scared to let the fermentation temper...,Sam Mason <samjbmason>
24,75,Never Mind The Anabolics,Performance-Enhancing India Pale Ale.,06/2012,"Never Mind the Anabolics, a 6.5% India Pale Al...",https://images.punkapi.com/v2/75.png,6.50,35,1012,1050.0,...,11.50,4.4,76.00,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 68, 'unit': ...",{'malt': [{'name': 'Extra Pale - Spring Blend'...,"[Grilled chicken salad with bacon and avocado,...",Mix the powders into a paste before adding to ...,Sam Mason <samjbmason>

## 과제 2 컨퍼런스 혹은 신입기수 세션에서 데이터를 끌어올 수 있는 API를 찾아보시고 찾기!



- response 응답의 구조를 파악하여 어떤 열을 어떻게 활용할 수 있을지 적어보세요!

- 찾은 API 명세서 -> 활용방안을 적어주시면 됩니다!

추천 :

요즘은 다른 거를 가져다가 쓰는 게 또 능력이죠

### <https://www.reddit.com/dev/api/>

### <https://developers.kakao.com/>

### <https://developers.naver.com/main/>

### <https://platform.openai.com/docs/introduction>

# 아래 작성해주시면 됩니다!!

### 사용할 API : https://openapi.naver.com/
네이버 API

### 사용할 기능 또는 api 응답에서 제공되는 변수 :
title: 블로그 포스트 제목
description: 블로그 포스트 내용 요약
bloggername: 블로거 이름
postdate: 블로그 포스트 작성 날짜

### 활용 방안 : 네이버 지도, 카카오맵, 구글 지도에 관한 사용자들의 평가, 그리고 각 앱을 사용하는 상황을 네이버 블로그를 크롤링하여 데이터 수집.

# 출처

- 내머리
- 챗지피티